Update ubuntu.yml

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -59,8 +59,6 @@ jobs:
           submodules: recursive
 
       - name: Setup ccache
-        # ccache is not supported on ARM yet
-        if: matrix.os != 'ubuntu-24.04-arm'
         uses: hendrikmuhs/ccache-action@v1.2
         with:
           key: "${{matrix.os}}-${{matrix.compiler}}-Release"
@@ -82,7 +80,9 @@ jobs:
         working-directory: ${{github.workspace}}/build_release
         run: cmake --build . --config Release -j4
 
-      - name: Test
+      - name: Run Tests and Save Results
         working-directory: ${{github.workspace}}/build_release
-        run: ./dropletTest
+        run: >
+          ./dropletTest --gtest_output=xml:test_results.xml || 
+          (echo "Tests failed or timed out" && exit 1)
         timeout-minutes: 10
